package BBS.info is
   --
   --  This file is auto generated by the build script.  It should not
   --  be edited by hand.
   --
   name           : constant String  := "Tiny Lisp";
   timestamp      : constant String  := "Tue Apr 27 13:47:28 MST 2021";
   build_date     : constant String  := "2021-Apr-27";
   version_string : constant String  := "V01.01";
   version_date   : constant Integer := 20210427;  -- yyyymmdd
   version_number : constant Integer := 2;
end;
