package BBS.info is
   pragma Pure;
   --
   --  This file is auto generated by the build script.  It should not
   --  be edited by hand.
   --
   name           : constant String  := "BBS Root";
   timestamp      : constant String  := "Tue Jul  5 19:42:37 MST 2022";
   build_date     : constant String  := "2022-Jul-05";
   version_string : constant String  := "V01.04";
   version_date   : constant Integer := 20220705;  -- yyyymmdd
   version_number : constant Integer := 3;
end;
