package BBS.info is
   pragma Pure;
   --
   --  This file is auto generated by the build script.  It should not
   --  be edited by hand.
   --
   name           : constant String  := "Tiny Lisp";
   timestamp      : constant String  := "Fri Sep  3 09:03:26 MST 2021";
   build_date     : constant String  := "2021-Sep-03";
   version_string : constant String  := "V01.01";
   version_date   : constant Integer := 20210903;  -- yyyymmdd
   version_number : constant Integer := 2;
end;
