package BBS.info is
   pragma Pure;
   --
   --  This file is auto generated by the build script.  It should not
   --  be edited by hand.
   --
   name           : constant String  := "BBS Root";
   timestamp      : constant String  := "Mon Jan 22 06:34:50 MST 2024";
   build_date     : constant String  := "2024-Jan-22";
   version_string : constant String  := "V01.05";
   version_date   : constant Integer := 20240122;  -- yyyymmdd
   version_number : constant Integer := 4;
end;
